### ISSUE TITLE
Broken table formatting in Connections Engagement Center - General configuration

### ISSUE THREAD

**Issue by Leyrer-PNP** [HCL-TECH-SOFTWARE/connections-doc#137]
### Description
The table for the General configuration of ICEC has layout issues.

### Observed 
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/117811070/bdd0c9c5-0d8c-4283-b06e-30308c804b98)

### Desired
Proper table formatting as shown in older versions of that page:
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/117811070/a6e9bfb7-04e3-4f09-be8e-d4f115242363)

 
### Topics
https://opensource.hcltechsw.com/connections-doc/v8-cr5/connectors/icec/cec-inst-gneral-configuration.html

**Comment by erika-dg** [comment]
Fixed, thanks for your help! Sample version: https://opensource.hcltechsw.com/connections-doc/v8/connectors/icec/cec-inst-gneral-configuration.html
