### ISSUE TITLE
Home page error messages table formatting broken

### ISSUE THREAD

**Issue by Leyrer-PNP** [HCL-TECH-SOFTWARE/connections-doc#138]
### Description
The table of "Home page error messages" is not formatted correctly.

### Observed 
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/117811070/880289c4-b068-427a-8f65-a6f056549925)

### Desired
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/117811070/43ed47f6-079d-47c2-aa75-d865872eeb63)
 
### Topics
https://opensource.hcltechsw.com/connections-doc/v8-cr4/admin/troubleshoot/r_error_codes_homepage.html

**Comment by erika-dg** [comment]
@Leyrer-PNP https://opensource.hcltechsw.com/connections-doc/v8-cr2/admin/troubleshoot/r_error_codes_homepage.html Thank you for going in to help fix the formatting issues! These are now published in all 8.0 versions.
