### ISSUE TITLE
Table is broken

### ISSUE THREAD

**Issue by umeli** [HCL-TECH-SOFTWARE/connections-doc#29]
**Note:** This form is for submitting issues about Connections 8 documentation, not Connections 8 itself.

### Description
looks like the table on this page is broken
https://opensource.hcltechsw.com/connections-doc/v8-cr1/connectors/admin/t_ms_teams_update_websphere_for_sso.html

### Observed 
![image](https://user-images.githubusercontent.com/710539/218754641-dc9db9ca-a84a-4964-b517-bee53ce60eda.png)

### Desired
should probably look more table like
 
### Topics
[URLs of topics affected.](https://opensource.hcltechsw.com/connections-doc/v8-cr1/connectors/admin/t_ms_teams_update_websphere_for_sso.html)

**Comment by david-bell-hcl** [comment]
@umeli - the table format should now be fixed.
