### ISSUE TITLE
Startpage points to CR1

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-doc#54]
**Note:** This form is for submitting issues about Connections MT documentation, not Connections MT itself.

### Description
Link to latest documentation on https://opensource.hcltechsw.com/connections-doc/ points to CR1

### Observed 
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/1975258/1fb7d968-308e-446a-9e7d-ef74d03b40e2)

**Comment by davidsayer57** [comment]
Thank you!   Updated!

**Comment by stoeps13** [comment]
Still points to CR1

**Comment by davidsayer57** [comment]
OK.. are folks still accessing that page?  I was going to delete it as we moved to https://opensource.hcltechsw.com/connections-doc/v8/ which has the "Click here to go to the latest" message to direct you to the cr2 doc.

**Comment by stoeps13** [comment]
When you have a bookmark to it for example. Or you click in the github repo: 
![image](https://github.com/HCL-TECH-SOFTWARE/connections-doc/assets/1975258/12f06eb2-bfce-49ac-b015-11b0bad0fec2)

**Comment by davidsayer57** [comment]
Thanks... Bookmarks, I was hoping they would update over time.   I didn't think of the Git link.   Please check again!

Thank you for bearing with me!
